### ISSUE TITLE
[feat]: Development Roadmap section

### ISSUE THREAD

**Issue by motuncoded** [VishwamAI/jobcity#15]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

I would like to work on the Development roadmap  section in the home page, I want to change the timeline structure.
![React-App-10-05-2024_07_55_AM](https://github.com/user-attachments/assets/a3285816-f039-4107-a5c3-7fa9625e56c7)

### Proposed Solution

I would provide a solution to the way it is structured.

### Do you want to work on this issue?

No

**Comment by kasinadhsarma** [comment]
we are developing every space you can contribute above we are developing every edge for all of us give your commitment to us

**Comment by imadityayadav** [comment]
hey @kasinadhsarma I have worked on this type of issue previously kindly assign this to me!!

**Comment by kasinadhsarma** [comment]
yeh! you can wait i will give you access

**Comment by kasinadhsarma** [comment]
![image](https://github.com/user-attachments/assets/e08c81a5-35f5-45d2-80ec-24a195c77ac0)

**Comment by kasinadhsarma** [comment]
![Screenshot from 2024-10-05 17-59-31](https://github.com/user-attachments/assets/d58d24c5-57eb-4ef7-9154-fa4dd8beb2f0)
@imadityayadav  has done huge @motuncoded  just do your devlopment also

**Comment by imadityayadav** [comment]
Add hactoberfest-accepted label to my PR

**Comment by kasinadhsarma** [comment]
![image](https://github.com/user-attachments/assets/c61bf3f3-3d7c-472a-94d9-1925c03da7cc)

**Comment by imadityayadav** [comment]
![Screenshot 2024-10-05 221648](https://github.com/user-attachments/assets/15a399d7-97a6-4746-a4b7-aa80ac290a95)
