### ISSUE TITLE
[FEATURE] Adding About us and contact us section 

### ISSUE THREAD

**Issue by w0wayush** [VishwamAI/jobcity#32]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

As I have gone through your website, there are no about us and contact us sections in it and you have added both of them in Navbar.

### Proposed Solution

I will create a responsive and sleek looking about us and contact us sections.

### Screenshots

Navbar's about us and contact us 
![image](https://github.com/user-attachments/assets/9b69f4b9-8a9f-4430-8934-1212786abd59)

No about us and contact us section in the website
![image](https://github.com/user-attachments/assets/573c0663-224b-49ad-8376-c69886baadc3)

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this (issue will not be assigned if this is skipped)

Please assign this issue to me, I would like to work on it.
Can you please add necessary labels for hacktober fest like hacktoberfest, hacktoberfest-2024, hacktoberfest-accepted, gssoc-ext. gssoc24.

**Comment by kasinadhsarma** [comment]
Yes you can

**Comment by w0wayush** [comment]
Created a PR for this added sections

**Comment by kasinadhsarma** [comment]
https://github.com/VishwamAI/jobcity/pull/34
