### ISSUE TITLE
[FEATURE] Navbar feature

### ISSUE THREAD

**Issue by w0wayush** [VishwamAI/jobcity#37]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

When clicked on navbar the navigation is too fast resulting in bad user experience

### Proposed Solution

I will add the feature in which the navigation after clicked on navbar redirects the user to the specific section smoothly which will effectively increase user's experience in the website.

Please assign this issue to me and add hacktober fest labels to this issue.

**Comment by kasinadhsarma** [comment]
yes i am @w0wayush does hacktoberfest is accepting your pull request

**Comment by kasinadhsarma** [comment]
ok you can do @w0wayush
