### ISSUE TITLE
[BUG] Get Started button not working

### ISSUE THREAD

**Issue by ParvamShah1** [VishwamAI/jobcity#47]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

The get started button on the home page is not working .
Please assign me this issue ,i would like to work on this .

### Steps to Reproduce

Include any relevant details like:

- What page you were on...
- What you were trying to do...
- What went wrong...
i was on the main home page.
i tapped the get started button but it did  not redirect me to the login page.

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

i would redirect the user to the login page when user clicks on get started button.

**Comment by kasinadhsarma** [comment]
yes you can work on this issue

**Comment by ParvamShah1** [comment]
can you assign this to me or my pr will get merged directly ?

**Comment by kasinadhsarma** [comment]
YES @ParvamShah1

**Comment by ParvamShah1** [comment]
npm is not working for your website please address this issue .

**Comment by ParvamShah1** [comment]
completed
