### ISSUE TITLE
Incorrect Redirection

### ISSUE THREAD

**Issue by Jils31** [VishwamAI/jobcity#48]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

When a user clicks on the Twitter icon in the footer (or wherever it's located), it leads to an incorrect landing page instead of the official Twitter profile page. The expected behavior is that clicking the Twitter icon should redirect users to the corresponding Twitter account of the website/company.

### Steps to Reproduce

Open the website in your browser.
Navigate to the section where the Twitter icon is displayed (typically in the header or footer).
Click on the Twitter icon.
Observe the behavior:
The page redirects to an incorrect or unexpected landing page instead of the correct Twitter profile.

### Screenshots

[Screencast from 2024-10-10 01-56-14.webm](https://github.com/user-attachments/assets/cab334d3-8e58-4daf-9628-73eba6f7cf00)

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

- Open the source code of the project in your code editor (VSCode, Sublime, etc.).
- Navigate to the file where the Twitter icon is implemented. This will typically be a footer component 
- Search for the section containing the Twitter icon. The icon is usually embedded inside an anchor (<a>) tag that controls the URL redirection.
- Replace the incorrect URL with the correct Twitter profile URL in the href attribute.

**Comment by kasinadhsarma** [comment]
did you fixed it

**Comment by w0wayush** [comment]
I would like to contribute to it, assign this task to me.

**Comment by kasinadhsarma** [comment]
ok i am assign to you @w0wayush
