### ISSUE TITLE
Add Scroll-to-Top Button for Improved User Experience

### ISSUE THREAD

**Issue by AnkitLuhar** [VishwamAI/jobcity#50]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

Yes, currently, users have to manually scroll back to the top of the webpage after exploring content, which can be inconvenient, especially on long pages. This hampers the overall user experience and makes the website less user-friendly.

### Proposed Solution

Implement a "Scroll-to-Top" button that appears when the user scrolls down the page. This button will enable users to quickly return to the top of the page with a single click, enhancing ease of navigation and overall website usability.

### Screenshots

![Screenshot (950)](https://github.com/user-attachments/assets/5a1398db-ff19-4439-bebb-1f322be6c992)

![Screenshot (951)](https://github.com/user-attachments/assets/196fb09a-e138-4436-8fa7-cf93c6e1fc94)

### Do you want to work on this issue?

YES

### If "yes" to above, please explain how you would technically implement this (issue will not be assigned if this is skipped)

**1>Frontend Development:**

-Create a floating button that becomes visible once the user scrolls down a certain threshold (e.g., 300px from the top).

-This button should be positioned in the bottom-right corner of the screen.

-When clicked, the button will trigger a smooth scroll animation back to the top of the page.

**2>Implementation Steps:**

-Use window.addEventListener('scroll', ...) to detect when the user has scrolled down the page.

-Use CSS for the button's design and positioning, ensuring it remains fixed and always visible when scrolling.

-Implement smooth scrolling functionality using window.scrollTo({ top: 0, behavior: 'smooth' }).

**3>Styling:**

-Apply a hover effect and transition to the button to make it visually appealing.

-The button can have a minimalistic design, such as an upward arrow icon, that fits the website's theme.

**Comment by kasinadhsarma** [comment]
@AnkitLuhar  you can continue it

**Comment by mayur1377** [comment]
Hey , added the feature [here](https://github.com/VishwamAI/jobcity/pull/51)!

**Comment by AnkitLuhar** [comment]
@mayur1377 is your PR merge first let me them merge,if it is merge then good i closed this issue and stop working on this issue.

**Comment by AnkitLuhar** [comment]
@kasinadhsarma basically u alot me this issue how any other member can work on same issue problem and Open PR, please sort this confusion!

**Comment by kasinadhsarma** [comment]
@AnkitLuhar basically fast people I can accept here do your work fast means I can accept here

**Comment by kasinadhsarma** [comment]
And also I don't know about @mayur1377 has completed on this issue

**Comment by mayur1377** [comment]
@kasinadhsarma, kindly add me as the assigned here

**Comment by AnkitLuhar** [comment]
@kasinadhsarma can I open PR for this issue or I have to leave this issue 😔!

**Comment by kasinadhsarma** [comment]
@AnkitLuhar you can work on dashboard it has lot of issues there
