### ISSUE TITLE
Add Loader in the WebSite.

### ISSUE THREAD

**Issue by AnkitLuhar** [VishwamAI/jobcity#54]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

currently the website directly open and without attract the user too much.

### Proposed Solution

 increase the user interest toward the website we implement the loader, which gives best aesthetic looks and also looks like user-friendly and modern website

### Screenshots

[screen-capture (13).webm](https://github.com/user-attachments/assets/a76c961b-7dac-4b12-83fa-8d57325a229b)

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this (issue will not be assigned if this is skipped)

firslty i make the jsx file for the Loader and give its styling which cover the whole screen and after some seconds the loader will be invisible and the main page of website will be shown,this can be done with help of useState() and conditional rendering & setTimeOut() & useEffect()

**Comment by kasinadhsarma** [comment]
sorry @AnkitLuhar  upto till now my system went down now it is fixed so that's why late reply you can do your work @AnkitLuhar
