### ISSUE TITLE
[BUG] Cant sign up properly 

### ISSUE THREAD

**Issue by ParvamShah1** [VishwamAI/jobcity#55]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

I cant sign up on your website there is CORS  on signing up .

Please assign me this issue i would like to work on it .
Thanks!

### Steps to Reproduce

Include any relevant details like:

- What page you were on...
- What you were trying to do...
- What went wrong...
i tried to sign in to the website and encountered the error .

### Screenshots

<img width="1280" alt="image" src="https://github.com/user-attachments/assets/800742dd-13aa-4b2a-b88c-d122933780b8">

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

i willl verify the CORS details

**Comment by kasinadhsarma** [comment]
yeh! foos @ParvamShah1
