### ISSUE TITLE
[FEATURE] Would like to add animation in all the section of the website

### ISSUE THREAD

**Issue by w0wayush** [VishwamAI/jobcity#59]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.
Currently theirs no animation in the website as we scroll from top to bottom which reduces intractability of the website of the users.  

### Proposed Solution
I would like to add animation on different section of the website using framer motion which would lead to better user experience.

### Do you want to work on this issue?
Yes
Please assign me this task.

**Comment by kasinadhsarma** [comment]
the animation is not currently needed dude we are  what we are building is job-city means automated job applying agent currently we are building it as MVP (minimum viable product ) so please do according to that @w0wayush  you can work on dashboard please
