### ISSUE TITLE
[BUG] <description>Compilation failed. Please help

### ISSUE THREAD

**Issue by bao1311** [VishwamAI/jobcity#71]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

Hi, I am a beginner to open-source projects. So I want to contribute to this project. Therefore, I created a fork repo and clone it onto my local machine. However, the compilation steps failed. Can you please help me?

### Steps to Reproduce

Include any relevant details like:

- I was on the main repo.
- npm install and npm start
- Failed

### Screenshots

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/b89d3e8e-0bb6-41ec-a3ed-66ed9393bd3f">

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

I do not know yet. I hope that some of you guys can help me!

**Comment by bao1311** [comment]
@kasinadhsarma Can you please help me? I also sent you an email. Thank you for your help!

**Comment by kasinadhsarma** [comment]
https://github.com/VishwamAI/jobcity/blob/main/INSTALLATION.md while check it out here and modify according to that
