### ISSUE TITLE
enhancement in app 

### ISSUE THREAD

**Issue by sunny7899** [VishwamAI/jobcity#8]
Hi @VishwamAI Can you assign this issue to me with Hactoberfest tag, or you can assign any other relevant issue?

**Comment by kasinadhsarma** [comment]
yeh! you can

**Comment by sunny7899** [comment]
@kasinadhsarma pls assign to me

**Comment by kasinadhsarma** [comment]
well devlop frontend devlopment for all

**Comment by kasinadhsarma** [comment]
![image](https://github.com/user-attachments/assets/31643c25-0c64-4d7f-8fa8-1b6858750a4b)

**Comment by kasinadhsarma** [comment]
just kick start @sunny7899 @kasinadhsarma @Vishwamai welcomes you

**Comment by sunny7899** [comment]
Sure @kasinadhsarma  will work on it pls assign issue to me

**Comment by sunny7899** [comment]
@kasinadhsarma  PR raised https://github.com/VishwamAI/jobcity/pull/17

**Comment by sunny7899** [comment]
@kasinadhsarma  can you please update it also. Your PR/MR was submitted to a repository that is not participating in Hacktoberfest. Maintainers need to add the hacktoberfest topic to the repository, or add the hacktoberfest-accepted label to your PR/MR.

**Comment by kasinadhsarma** [comment]
i have been updated can i know about it @sunny7899
